#!/bin/bash
clear
echo Welcome to the FIND script
echo -n "Enter the location (such as /home) where the search should start "
read STARTLOCATION
echo -n "What is the name of the file to search for? "
read FILENAME
echo "Search starting for the $FILENAME file in the $STARTLOCATION directory"
find $STARTLOCATION -name $FILENAME 2>/dev/null
